### PR TITLE
update README.md #1

### PR DESCRIPTION
**Pull request by aakhtar3**

### CODE REVIEW

**Comment by aakhtar3** [comment]
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by acrosman** [comment]
Thank you for submitting this, but another edit came in on that file.  Would you mind rebasing to the current version and merging your changes.

I'm not sure where you ran into the message about Hacktoberfest. All valid PRs against public repositories are counted toward your goal:
> Pull requests can be made in any GitHub-hosted repositories/projects. As long as the project is public and GitHub-hosted, your pull requests will count toward your participation. 

From [Project details page.](https://hacktoberfest.digitalocean.com/details#details)

**Comment by aakhtar3** [comment]
@acrosman rebased
The admin will need to update the repo by adding the topic to `hacktoberfest`
Screen Shot 2020-10-04 at 10 21 32 AM

Screen Shot 2020-10-04 at 10 21 41 AM

**Comment by aakhtar3** [comment]
@acrosman now I am seeing a valid PR for hacktoberfest
Is this PR ready for merge?

**Comment by aakhtar3** [comment]
Your PR has not yet been accepted by a maintainer. A maintainer can accept your PR by merging it, adding the "hacktoberfest-accepted" label to it, or approving it.

**Comment by acrosman** [comment]
Thank you for rebasing to resolving the conflict, but your commit removes a bunch of content.  Arguably that content is better placed in the Contributing file than in the main readme, but I would like to not lose those additions.  Can you either migrate the instructions about how to contribute to the other file or at the very least ensure your changes do not remove those.

With the Hacktoberfest tag in place you should get credit as long as I don't mark it to be rejected by the organizers. As I understand the revised rules it will still eventually mature on its own if I take no action. You may find that maintainers are more interested in the quality of the content than ensuring you earn a free t-shirt in the first few days of the month.

**Comment by aakhtar3** [comment]
@acrosman I moved the contribution documentation from the README.md to the `contributing.md.md` file

**Comment by acrosman** [comment]
Thank you for seeing this through.

**Pull request merged**
